trigger:
  branches:
    include:
     - master
  paths:
    include:
     - AntidoteVerifier/*

pool: Studio-OX

variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  solution : '**/Sdl.Community.AntidoteVerifier.sln'
  pluginName: 'AntidoteVerifier'
  artifactName: 'AntidoteVerifier.sdlplugin'

steps:
  - template: include-buid-steps.yml